#!/usr/bin/env python3
"""Copy the card and its artwork into the integration: custom_components/sun_cycle_bg/www/

Since 2.0.0 the repository is one Home Assistant integration (HACS category
Integration). HACS installs `custom_components/sun_cycle_bg/`, and the
integration serves `www/` at /sun_cycle_bg/ and keeps a dashboard resource for
its loader (www/loader.js), so the card, its pictures,
the profile store and the settings page arrive together.

The card is written in src/, the pictures live in demo/assets/ (the tuning
pages use them too). www/ holds copies, and a copy that nobody refreshes ships
the previous card under the new version, so CI runs this script and fails when
it changes anything. www/panel.js is a source, not a copy; this script leaves
it alone. www/base.js and www/loader.js are generated here as well: the loader
imports base.js and the card statically, with the
card's version in the URL, so the card is part of the loader's own module graph
(no nested dynamic import) and an update fetches the new card.

    python3 tools/make_dist.py        # before every commit that touches src/ or the art

Pictures are flat in www/ (planets included): the card asks for
`<base><body>.png` first and retries `planets/<body>.png` only for manual
installs copied from an older dist/.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).parent.parent
WWW = ROOT / "custom_components" / "sun_cycle_bg" / "www"

# (path in the repository, name in www/)
ZAWARTOSC = [("src/sun-cycle-bg.js", "sun-cycle-bg.js")]
for nazwa in ("sun.png", "moon.png", "milky-way.jpg", "milky-way-cutout.webp",
              "leaves-autumn.webp", "leaves-spring.webp", "leaves-summer.webp"):
    ZAWARTOSC.append((f"demo/assets/{nazwa}", nazwa))
for ciało in ("mercury", "venus", "earth", "mars", "jupiter", "saturn",
              "uranus", "neptune", "pluto"):
    ZAWARTOSC.append((f"demo/assets/planets/{ciało}.png", f"{ciało}.png"))
ZAWARTOSC.append(("demo/assets/MILKY-WAY-CREDIT.md", "CREDITS.md"))
# written by hand, kept in www/ itself
ZRODLA_W_WWW = ("panel.js",)

BASE_JS = """/* Generated by tools/make_dist.py. Imported first by loader.js: the card reads
   SUN_CYCLE_BG_BASE when it is evaluated, to find its pictures next to it. */
window.SUN_CYCLE_BG_BASE = new URL('./', import.meta.url).pathname;
"""

LOADER_JS = """/* Generated by tools/make_dist.py: loads the sun-cycle-bg card from the
   sun_cycle_bg integration.

   The integration keeps this file as a dashboard resource (and the settings
   panel imports it itself). Static
   imports, in this order: base.js tells the card where its pictures are, then
   the card itself, with its version in the URL so an update is fetched anew.
   Should the card still be missing once this module runs (a load that never
   finished was seen on a test instance), it is imported once more. */
import './base.js';
import './sun-cycle-bg.js?v=__WERSJA__';

if (!customElements.get('sun-cycle-bg-card')) {
  console.warn('sun-cycle-bg: the card is not registered after loading; loading it again');
  import('./sun-cycle-bg.js?v=__WERSJA__&retry=' + Date.now()).catch((err) =>
    console.error('sun-cycle-bg: the card did not load', err));
}
"""


def wersja() -> str:
    pierwsza = (ROOT / "src" / "sun-cycle-bg.js").read_text().split("\n", 1)[0]
    import re
    m = re.match(r"/\* sun-cycle-bg (\d+\.\d+\.\d+)", pierwsza)
    if not m:
        raise SystemExit("brak wersji w pierwszej linii src/sun-cycle-bg.js")
    return m.group(1)


def main() -> int:
    WWW.mkdir(parents=True, exist_ok=True)
    brakuje = [z for z, _ in ZAWARTOSC if not (ROOT / z).exists()]
    brakuje += [f"www/{n}" for n in ZRODLA_W_WWW if not (WWW / n).exists()]
    if brakuje:
        raise SystemExit("brak plików: " + ", ".join(brakuje))
    razem = 0
    for nazwa, tresc in (("base.js", BASE_JS), ("loader.js", LOADER_JS.replace("__WERSJA__", wersja()))):
        cel = WWW / nazwa
        if not cel.exists() or cel.read_text() != tresc:
            cel.write_text(tresc)
    for src, dst in ZAWARTOSC:
        cel = WWW / dst
        dane = (ROOT / src).read_bytes()
        if not cel.exists() or cel.read_bytes() != dane:
            cel.write_bytes(dane)
        razem += len(dane)
        print(f"  {dst:28} {len(dane) // 1024:5} kB")
    print(f"{WWW.relative_to(ROOT)}: {len(ZAWARTOSC)} plików, {razem // 1024} kB (+ base.js, loader.js {wersja()}, {', '.join(ZRODLA_W_WWW)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
